# Workout Logging Workflow

trigger:
  type: manual
  value: "after workout"

actions:
  - Log workout type and duration
  - Record exercises and reps
  - Track calories burned
  - Update progress toward goals
  - Provide positive feedback

context:
  category: fitness
  priority: high
