# Article Summary Workflow

trigger:
  type: manual
  value: "user shares article"

actions:
  - Fetch article content
  - Identify main thesis
  - Extract key points
  - Generate summary
  - Store in notes

context:
  category: reading
  priority: medium
