# Book Notes Workflow

trigger:
  type: manual
  value: "user finishes chapter or requests notes"

actions:
  - Create chapter summary
  - Extract key concepts
  - Generate actionable insights
  - Connect to existing knowledge
  - Update reading progress

context:
  category: learning
  priority: medium
