# Weekly Review Workflow

trigger:
  type: time
  value: "Sunday 6:00 PM"

actions:
  - Review completed tasks from the week
  - Identify incomplete items and reschedule
  - Gather new tasks and priorities
  - Plan major goals for next week
  - Clear mental clutter

context:
  category: review
  priority: medium
