# Daily Planning Workflow

trigger:
  type: time
  value: "8:30 AM"

actions:
  - Retrieve all pending tasks
  - Group by priority
  - Group by context (home/work/errands)
  - Estimate time for each task
  - Create time blocks
  - Present organized day plan

context:
  category: planning
  priority: high
