# Quick Task Capture Workflow

trigger:
  type: keyword
  value: "capture"

actions:
  - Listen for task description
  - Identify task category
  - Set default priority
  - Create reminder/task
  - Confirm creation

context:
  category: task-management
  priority: high
