# Server Health Check Workflow

trigger:
  type: time
  value: "every 5 minutes"

actions:
  - Check CPU usage across all servers
  - Check memory utilization
  - Check disk space and I/O
  - Check network connectivity
  - Check running services status
  - Report anomalies

context:
  category: monitoring
  priority: high
  severity-check: true
