# Meeting Preparation Workflow

trigger:
  type: time
  value: "15 minutes before meeting"

actions:
  - Send reminder notification
  - Share meeting agenda
  - Check participant availability
  - Prepare meeting room/materials

context:
  category: preparation
  priority: high
