# Meeting Follow-up Workflow

trigger:
  type: manual
  value: "after meeting ends"

actions:
  - Generate meeting minutes
  - Extract action items
  - Assign tasks to participants
  - Schedule follow-up reminders
  - File meeting notes

context:
  category: followup
  priority: medium
