# Weekly Progress Workflow

trigger:
  type: time
  value: "Sunday 8:00 PM"

actions:
  - Compile weekly workout summary
  - Compare to previous weeks
  - Celebrate achievements
  - Adjust next week's plan
  - Send motivation

context:
  category: progress
  priority: medium
