# Daily Review Workflow

trigger:
  type: time
  value: "8:00 PM"

actions:
  - Review today's vocabulary
  - Practice difficult words
  - Complete quiz
  - Log study time
  - Update streak count

context:
  category: learning
  priority: high
