# Weekly Progress Workflow

trigger:
  type: time
  value: "Sunday 7:00 PM"

actions:
  - Review weekly progress
  - Identify weak areas
  - Adjust study plan
  - Celebrate streak milestone
  - Set goals for next week

context:
  category: progress
  priority: medium
