# Article Writing Workflow

trigger:
  type: keyword
  value: "write-article"

actions:
  - Research topic thoroughly
  - Create detailed outline
  - Write engaging introduction
  - Develop main body with subheadings
  - Write compelling conclusion
  - Add SEO elements (keywords, meta)
  - Provide content improvement suggestions

context:
  category: content
  priority: medium
