# Video Script Creation Workflow

trigger:
  type: keyword
  value: "create-script"

actions:
  - Understand video topic and goal
  - Create hook and intro
  - Structure main content
  - Add visual cues and B-roll suggestions
  - Write call-to-action
  - Estimate video length
  - Provide editing notes

context:
  category: content
  priority: medium
