# Weekly Content Planning Workflow

trigger:
  type: time
  value: "Monday 9:00 AM"

actions:
  - Review previous week performance
  - Identify trending topics in niche
  - Brainstorm content ideas
  - Plan content calendar for the week
  - Assign topics to content types

context:
  category: planning
  priority: high
