# Trip Planning Workflow

trigger:
  type: manual
  value: "user wants to plan a trip"

actions:
  - Gather destination preferences
  - Research attractions and activities
  - Create preliminary itinerary
  - Estimate costs
  - Generate packing list

context:
  category: planning
  priority: high
