# Trip Reminder Workflow

trigger:
  type: time
  value: "1 day before trip"

actions:
  - Send final reminder
  - Share itinerary summary
  - Check weather forecast
  - Confirm reservations
  - Provide packing checklist

context:
  category: reminder
  priority: high
