# Daily Alert Digest Workflow

trigger:
  type: time
  value: "9:00 AM"

actions:
  - Aggregate alerts from past 24 hours
  - Categorize by severity and service
  - Identify recurring issues
  - Summarize action taken
  - Highlight unresolved alerts

context:
  category: alerts
  priority: medium
